export const ADD_PATIENT= "ADD_PATIENT";
export const DELETE_PATIENT= "DELETE_PATIENT";
export const ADD_APPOINTMENT= "ADD_APPOINTMENT";
export const DELETE_APPOINTMENT= "DELETE_APPOINTMENT";
export const ADD_DOCTOR= "ADD_DOCTOR";
export const DELETE_DOCTOR= "DELETE_DOCTOR";